name: Inverter Control Scheduler

# This section defines when the workflow will run.
on:
  # This "workflow_dispatch" section is what creates the manual "Run workflow" button.
  workflow_dispatch:
    # This "inputs" block creates the dropdown menu.
    inputs:
      action:
        description: 'Manual Action to Run'
        required: true
        default: 'status' # Default to a safe, non-changing action
        type: choice
        options:
        - status # Get current status
        - solar  # Force set to Solar mode
        - sbu    # Force set to SBU mode

  # This is the original scheduler. It will continue to run automatically.
  schedule:
    # 9:00 AM Bangkok (UTC+7) is 2:00 AM UTC.
    - cron: '40 1 * * *'
    # 6:00 PM (18:00) Bangkok (UTC+7) is 11:00 AM UTC.
    - cron: '0 11 * * *'

jobs:
  run-inverter-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      # This step now passes the dropdown selection to the Python script.
      # For scheduled runs, github.event.inputs.action is empty, so the script runs its default time logic.
      - name: Execute Inverter Control Script
        env:
          INVERTER_TOKEN: ${{ secrets.INVERTER_TOKEN }}
        run: python inverter_control.py ${{ github.event.inputs.action }}
